---
title: "Bilgi yönetim Sistemleri - Bitirme Projesi Rapor"
author: "Kadir Karaberzat 2004010\n
Hasan Orcan Güzey 2004010\n
Emir Can Yarar 200401069\n
İsmail Tekin 2004010"
---

# **İş Probleminin Tanımı: FigTree**

**FigTree**, danışan şirketlerin çalışanlarının performansını ve tatminini analiz ederek, gerekli optimizasyonları tespit edip interaktif tablolar şeklinde sunan bir danışmanlık firmasıdır.

1. *Performans Ölçme*: Çalışanların performansını objektif kriterlere göre değerlendiriyoruz.
2. *Tatmin Analizi*: Çalışan tatminini anketler ve görüşmeler aracılığıyla ölçüyoruz.
3. *Şirket İçi Çalışan Davranışı Geliştirme Önerisi*: Verimliliği artırmak için davranışsal stratejiler öneriyoruz.
4. *Terfi ve İşten Çıkarma Önerisi*: Şirketin ihtiyaçlarına göre terfi veya işten çıkarma önerilerinde bulunuyoruz. Gelir modelimiz, danışmanlık yaptığımız şirketlerden **saatlik bazda ücret** almak üzerine kuruludur. Kullandığımız bilgi yönetim sisteminin özellikleri aşağıdaki gibidir:

## **Metabase Özellikleri**

Metabase, kullanıcılara SQL bilgisi olmadan bile veri sorgulama imkanı sunar. **Görsel Sorgu Oluşturucu**, interaktif **panolar**, **modeller** ve daha birçok özellikle donatılmıştır. Ayrıca, sonuçları ve modelleri önbelleğe alabilir, kullanıcı davranışlarını denetleyebilir ve resmi içerikleri doğrulayabilirsiniz.

## **Desteklenen Veritabanları ve Teknolojiler**

Metabase, **Amazon Athena**, **Amazon Redshift**, **Apache Spark**, **BigQuery**, **MySQL**, **PostgreSQL**, **SQLite** ve daha birçok veri kaynağına doğrudan bağlanabilir. Ayrıca, CSV dosyalarını yükleyerek veri tabanları arasında daha fazla veri kaynağını birleştirebilirsiniz.

## **API Yetenekleri**

Metabase API'si, kullanıcıların programatik istekler için anahtarlar oluşturmasına, özel sorgular çalıştırmasına ve Metabase örneklerini otomatik olarak sağlamasına olanak tanır. **API, sık sık değişmez ve neredeyse hiç kaldırılmaz,** ancak API'ye dayalı kod yazanların gelecekte kodlarını güncellemeleri gerekebilir.

## **Tercih Sebepleri**

Metabase, kullanım kolaylığı, maliyet etkinliği, esneklik ve çekici raporlar ve panolar sunması gibi nedenlerle tercih edilmektedir. Ayrıca, açık kaynaklı bir çözüm olması, düşük bakım maliyetleri ve kolay gömülme özellikleri ile öne çıkmaktadır.

Metabase, iş zekası araçları arasında güçlü bir seçenektir ve veri analizi ve *görselleştirme ihtiyaçlarınız için değerlendirmeye* değer bir araçtır.

# **IBM Kurgusal Veri Seti Analizi**

Bu veri seti, IBM veri bilimcileri tarafından oluşturulmuş kurgusal bir veri setidir. Amacımız, bu veri setini bir SQLite veritabanında Metabase üzerinde oluşturmak ve R programlama dili kullanarak bağlantı kurmaktır.

## **Veritabanı Tablosu Sütunları**

Veritabanı tablosu, çalışanların çeşitli özelliklerini ve şirket içindeki durumlarını yansıtan aşağıdaki sütunlara sahiptir:

-   **Yaş** (`Age`)
-   **Ayrılma** (`Attrition`)
-   **İş Seyahati** (`BusinessTravel`)
-   **Günlük Ücret** (`DailyRate`)
-   **Departman** (`Department`)
-   **Evden Uzaklık** (`DistanceFromHome`)
-   **Eğitim** (`Education`)
-   **Eğitim Alanı** (`EducationField`)
-   **Çalışan Sayısı** (`EmployeeCount`)
-   **Çalışan Numarası** (`EmployeeNumber`)
-   **Çevre Tatmini** (`EnvironmentSatisfaction`)
-   **Cinsiyet** (`Gender`)
-   **Saatlik Ücret** (`HourlyRate`)
-   **İşe Katılım** (`JobInvolvement`)
-   **İş Seviyesi** (`JobLevel`)
-   **İş Rolü** (`JobRole`)
-   **İş Tatmini** (`JobSatisfaction`)
-   **Medeni Durum** (`MaritalStatus`)
-   **Aylık Gelir** (`MonthlyIncome`)
-   **Aylık Ücret** (`MonthlyRate`)
-   **Çalışılan Şirket Sayısı** (`NumCompaniesWorked`)
-   **18 Yaş Üstü** (`Over18`)
-   **Fazla Mesai** (`OverTime`)
-   **Maaş Artış Yüzdesi** (`PercentSalaryHike`)
-   **Performans Değerlendirmesi** (`PerformanceRating`)
-   **İlişki Tatmini** (`RelationshipSatisfaction`)
-   **Standart Saatler** (`StandardHours`)
-   **Hisse Senedi Seçenek Seviyesi** (`StockOptionLevel`)
-   **Toplam Çalışma Yılları** (`TotalWorkingYears`)
-   **Son Yıldaki Eğitim Süreleri** (`TrainingTimesLastYear`)
-   **İş-Yaşam Dengesi** (`WorkLifeBalance`)
-   **Şirketteki Yıllar** (`YearsAtCompany`)
-   **Güncel Roldeki Yıllar** (`YearsInCurrentRole`)
-   **Son Terfi Tarihinden İtibaren Geçen Yıllar** (`YearsSinceLastPromotion`)
-   **Mevcut Yöneticiyle Geçirilen Yıllar** (`YearsWithCurrManager`)

Bu veri seti, çalışanların şirket içindeki kariyer yollarını ve performanslarını analiz etmek için kullanılabilir. Ayrıca, şirket politikalarının çalışan memnuniyeti ve devamlılığı üzerindeki etkilerini değerlendirmek için de faydalı bir kaynaktır.

Kullanacağımız veri setinin linki: <https://www.kaggle.com/datasets/pavansubhasht/ibm-hr-analytics-attrition-dataset/data>

# **Veri Seti Detayları** 

**Age (Yaş):** Çalışanın yaşı, bağlılık üzerinde etkili olabilir.

**Attrition (Bağlılık):** Çalışanın şirkette kalıp kalmadığını gösteren hedef değişken.

**BusinessTravel (İş Seyahati):** İş seyahatlerinin sıklığı, çalışan memnuniyetini ve bağlılığını etkileyebilir.

**Department (Departman):** Çalışanın çalıştığı departman, bağlılık üzerinde etkili olabilir.

**DistanceFromHome (Evin Uzaklığı):** Evden işe olan mesafe, çalışan memnuniyeti ve bağlılığı üzerinde etkili olabilir.

**Education (Eğitim):** Eğitim seviyesi, çalışanların kariyer beklentilerini ve bağlılıklarını etkileyebilir.

**EnvironmentSatisfaction (Çevresel Memnuniyet):** Çalışma ortamından memnuniyet, çalışan bağlılığı üzerinde doğrudan etkilidir.

**JobInvolvement (İşe Katılım):** Çalışanın işine olan bağlılığı ve katılımı.

**JobLevel (İş Seviyesi):** Çalışanın hiyerarşideki yeri, bağlılığı etkileyebilir.

**JobRole (İş Rolü):** Çalışanın rolü ve sorumlulukları, bağlılık üzerinde etkili olabilir.

**JobSatisfaction (İş Memnuniyeti):** İş memnuniyeti, çalışan bağlılığının önemli bir göstergesidir.

**MaritalStatus (Medeni Durum):** Çalışanın medeni durumu, iş ve özel hayat dengesini etkileyebilir.

**MonthlyIncome (Aylık Gelir):** Çalışanın geliri, iş memnuniyeti ve bağlılığı üzerinde etkili olabilir.

**OverTime (Fazla Mesai):** Fazla mesai yapma durumu, çalışan memnuniyetini etkileyebilir.

**WorkLifeBalance (İş-Yaşam Dengesi):** İş ve özel hayat dengesinin memnuniyeti.

**YearsAtCompany (Şirketteki Yıllar):** Çalışanın şirkette ne kadar süre çalıştığı, bağlılık üzerinde önemli bir faktördür.

**YearsInCurrentRole (Mevcut Roldeki Yıllar):** Mevcut pozisyonda geçirilen süre.

**YearsSinceLastPromotion (Son Terfiden İtibaren Geçen Yıllar):** Terfi sıklığı, çalışan memnuniyetini etkileyebilir.

**YearsWithCurrManager (Mevcut Yönetici ile Geçirilen Yıllar):** Mevcut yönetici ile çalışılan süre, çalışan memnuniyeti ve bağlılığı üzerinde etkili olabilir.

| Kolon                     | Non-Null Sayısı | Dtype   |
| -------------------------- | -------------- | ------- |
| Age                        | 1470           | int64   |
| Attrition                  | 1470           | object  |
| BusinessTravel             | 1470           | object  |
| DailyRate                  | 1470           | int64   |
| Department                 | 1470           | object  |
| DistanceFromHome           | 1470           | int64   |
| Education                  | 1470           | int64   |
| EducationField             | 1470           | object  |
| EmployeeCount              | 1470           | int64   |
| EmployeeNumber             | 1470           | int64   |
| EnvironmentSatisfaction    | 1470           | int64   |
| Gender                     | 1470           | object  |
| HourlyRate                 | 1470           | int64   |
| JobInvolvement             | 1470           | int64   |
| JobLevel                   | 1470           | int64   |
| JobRole                    | 1470           | object  |
| JobSatisfaction            | 1470           | int64   |
| MaritalStatus              | 1470           | object  |
| MonthlyIncome              | 1470           | int64   |
| MonthlyRate                | 1470           | int64   |
| NumCompaniesWorked         | 1470           | int64   |
| Over18                     | 1470           | object  |
| OverTime                   | 1470           | object  |
| PercentSalaryHike          | 1470           | int64   |
| PerformanceRating          | 1470           | int64   |
| RelationshipSatisfaction   | 1470           | int64   |
| StandardHours              | 1470           | int64   |
| StockOptionLevel           | 1470           | int64   |
| TotalWorkingYears          | 1470           | int64   |
| TrainingTimesLastYear      | 1470           | int64   |
| WorkLifeBalance            | 1470           | int64   |
| YearsAtCompany             | 1470           | int64   |
| YearsInCurrentRole         | 1470           | int64   |
| YearsSinceLastPromotion    | 1470           | int64   |
| YearsWithCurrManager       | 1470           | int64   |

# **Veri Setinin İthali**

Veri setimiz ".csv" formatında kaggle'dan temin edildikten sonra R aracılığıyla incelenmiş, ardından SQLite veritabanına dönüştürülmüştür. Öncelikle sunucumuza SSH ile bağlanıp oluşturduğumuz ".sqlite" dosyasını gönderdik. Ardından sunucuda docker komutlarını kulanarak Metabase'i bulunduran konteynıra bu dosyayı ekledik. 51.75.71.10:3000 adresindeki arayüzümüze giriş yaparak veritabanımızı Metabase'e tanıttık.

# **Projemizin Temel Amacı: Çalışan Verimliliği Analizi**

Projemizin temel amacı işverenlerin çalışanlardan maksimum verim alabilmesidir. Bu doğrultuda analiz planlarımız aşağıda belirtilmiştir:

1. **Çalışan Verimliliğini Etkileyen Faktörlerin Analizi**
   - *Tanımlayıcı İstatistikler:* Yaş, cinsiyet, eğitim düzeyi, medeni durum gibi demografik değişkenlerin çalışan verimliliği üzerindeki etkisinin incelenmesi.
   - *Korelasyon Analizi:* Çalışan verimliliğini temsil eden değişkenlerle (örneğin, İş Memnuniyeti, İşe Katılım) diğer değişkenler arasındaki ilişkinin incelenmesi.
   - *Görselleştirme:* Verilerin kutu grafikleri, histogramlar ve dağılım grafikleri gibi grafiklerle görselleştirilmesi. Örneğin, Aylık Gelir ve İş Memnuniyeti arasındaki ilişkiyi incelemek için dağılım grafiği kullanımı.

2. **Bağlılık Analizi**
   - *Bağlılık Oranlarının İncelenmesi:* Hangi grupların (örneğin, İş Seyahati, Departman) daha yüksek bağlılık oranlarına sahip olduğunun belirlenmesi.

3. **Çalışan Memnuniyeti ve Verimlilik**
   - *Çalışma Ortamı Faktörlerinin İncelenmesi:* Çalışan verimliliği üzerindeki etkileri analiz etmek için Çevre Memnuniyeti, İş Memnuniyeti, İş-Özel Hayat Dengesi gibi faktörlerin incelenmesi.
   - *Anket Sonuçları Analizi:* Çevre Memnuniyeti, İş Memnuniyeti, İş-Özel Hayat Dengesi gibi memnuniyet ölçütlerinin dağılımının incelenmesi ve bu ölçütlerin performansla ilişkisinin analiz edilmesi.

4. **İş ve Özel Hayat Dengesi**
   - *İş-Özel Hayat Dengesi Analizi:* Çalışanların iş-yaşam dengesi ile verimlilik arasındaki ilişkinin incelenmesi.
   - *Fazla Mesai Yapan Çalışanların İş-Özel Hayat Dengesi ve Memnuniyet Durumlarının Analizi:* Fazla mesai yapan çalışanların iş-yaşam dengesi ve memnuniyet durumlarının analiz edilmesi.

5. **Performans ve Kariyer Gelişimi**
   - *Yıllık Performans İncelemesi:* Performans Değerlendirmesi ve diğer performans ölçütlerinin analiz edilmesi.
   - *Terfi ve Kariyer Gelişimi:* Son Terfi Tarihinden Sonra Geçen Yıllar ve Mevcut Pozisyonda Geçen Yıllar gibi değişkenlerin çalışan memnuniyeti ve verimliliği üzerindeki etkisinin incelenmesi.

6. **Sonuçlar**
   - *Analiz Sonuçlarının Raporlanması:* Elde edilen bulguların özetlenmesi ve işverenler için önemli çıkarımların vurgulanması.

